name: dns_changer
description: "Multiplatform DNS Changer."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  drift: ^2.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  launch_at_startup: ^0.3.1
  path: ^1.9.0
  path_provider: ^2.1.3
  process_run: ^1.2.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  sqlite3_flutter_libs: ^0.5.24
  top_snackbar_flutter: ^3.1.0
  tray_manager: ^0.3.0
  url_launcher: ^6.3.1
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: null
  custom_lint: null
  drift_dev: ^2.18.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/language/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
